export function enrich(state){
 const g=state.trips.find(t=>t.name==='Guadarrama - Prueba');
 Object.assign(g,{description:'Ruta circular de un día por la Sierra de Guadarrama. Apto para todos los niveles con tramos opcionales.',notes:'Quedamos a las 8:00 en el aparcamiento de Las Dehesas. Desayuno antes de salir.',expenses:[{id:'gasolina',type:'Combustible',description:'Gasolina',amount:30,confirmed:false},{id:'comida',type:'Comidas',description:'Comida ruta',amount:20,confirmed:false}],routes:[{id:'dehesas',name:'Circular Las Dehesas',distance:35,duration:'4h',elevation:700,fuel:1,difficulty:'Media',notes:'Ruta circular con vistas a la bola del mundo.',mapCenter:[40.759,-4.056]}]});
 const p=state.trips.find(t=>t.name==='Pirineos Aragoneses - Octubre');
 Object.assign(p,{end:'2026-10-28',description:'Salida de 4 días por los valles del Pirineo aragonés. Rutas de montaña con tramos técnicos y paisajes espectaculares. Nivel medio-alto.',notes:'Reunión viernes 19h en el alojamiento. Llevar cadenas y neumáticos de tacos. Gasolina: llenar en Sallent de Gállego.',lodgings:[{id:'pinos',name:'Casa rural Los Pinos',address:'Calle Mayor 5, Sallent de Gállego',total:720,perPerson:120,confirmed:true}],expenses:[{id:'comidas-pirineos',type:'Comidas',description:'Comidas y cenas',amount:100,confirmed:true},{id:'gasolina-pirineos',type:'Combustible',description:'Gasolina ida y vuelta',amount:80,confirmed:false},{id:'peajes',type:'Peajes',description:'Peajes autopista',amount:25,confirmed:true}],routes:[{id:'piedrafita',name:'Vuelta al Ibón de Piedrafita',distance:65,duration:'6h',elevation:1800,fuel:2,difficulty:'Difícil',notes:'Tramo técnico final con rocas. Llevar protectores.',mapCenter:[42.699,-.323]},{id:'sendero',name:'Sendero del Valle',distance:40,duration:'4h',elevation:900,fuel:1,difficulty:'Media',notes:'Ruta de calentamiento.'}]});
 const s=state.trips.find(t=>t.name==='Sierra Morena - Primavera');
 Object.assign(s,{end:'2026-05-17',description:'Ruta de primavera por Sierra Morena. Tramos rápidos y senderos técnicos.',notes:'Salida completada con éxito.',lodgings:[{id:'refugio',name:'Refugio Santa Elena',address:'Despeñaperros',total:360,perPerson:90,confirmed:true}]});
 return state;
}
