import {enrich} from './reference-data.js';
const person=(name,bike='',status='Confirmado',extra={})=>({id:crypto.randomUUID(),name,bike,status,phone:'',notes:'',companion:false,organizer:false,userId:'',...extra});
const organizer=(name='Organizador',bike='KTM 300 EXC')=>person(name,bike,'Confirmado',{organizer:true,userId:name==='Fernando Fernandez'?'local-user':''});
export function initialState(){return enrich({version:1,profile:{userId:'local-user',name:'Fernando Fernandez',email:'ffernandez333@gmail.com',phone:'',bike:'KTM 250 TPI 2021',notes:'Pathfinder',role:'Administrador'},trips:[
 {id:'6a99cd0bfaca65d20312a73a',name:'Bostronizo',zone:'Cantabria',start:'2026-10-09',end:'2026-10-12',status:'Confirmada',description:'3 dias de ruta enduro en Bostronizo. Habra barbacoa el mejor dia que caiga. Cada uno que se lleve su desayuno, comida, cena y bebidas. Alli no hay nada y el pueblo mas cercano esta a 15min en coche. Tampoco hay gasalinera ni lavar motos. Gaslinera por las rutas aunque si os llevais garrafa mejor. En las dos casas hay para cocinar de todo y las camas hay sabanas. Llevar toalla. Comeremos de bocata y luego cena para recuperar. Hay alternativas en todas las rutas.',notes:'',participants:[person('Kiko','Ktm 300'),person('Luixfco','Gasgas','Pendiente',{companion:true,notes:'Ninguna'}),person('Juan Carlos Nieto','KTM EXC 300'),person('Javi_Jarvis','Husqvarna TE300i','Confirmado',{notes:'Llevo material de repuesto por si acaso.'}),person('Jesús Garcia Martin','Yamaha wrf'),organizer('Fernando Fernandez','KTM 250 TPI 2021')],lodgings:[{id:'casa',name:'Casa Rural Los Maestros',address:'',url:'',contact:'',checkin:'',checkout:'',total:'',perPerson:22,notes:'',confirmed:true}],expenses:[{id:'alojamiento',type:'Alojamiento',description:'Casa Los Maestros (22€/persona/día)',amount:22,confirmed:false}],routes:[{id:'sabado',name:'Sabado',distance:70,difficulty:'Media',elevation:'',duration:'',fuel:0,notes:'Sábado haremos primero bucle Toranzo. El bucle Silio para el domingo. Si hay ganas sorpresita final.',file:'/assets/sabado.gpx',filename:'Sabado_2_70km.gpx'},{id:'domingo',name:'Domingo',distance:58,difficulty:'Media',notes:'Domingo',file:'/assets/domingo.gpx',filename:'Domingo_58km.gpx'},{id:'lunes',name:'Lunes',distance:37,difficulty:'Media',notes:'',file:'/assets/lunes.gpx',filename:'Lunes_37km.gpx'}]},
 {id:'6a99c6f46ef0815af879555b',name:'Guadarrama - Prueba',zone:'Cercedilla',start:'2026-09-20',end:'',status:'Abierta',description:'',notes:'',participants:[person('Pedro L.','GasGas EC 300'),organizer()],lodgings:[],expenses:[],routes:[]},
 {id:'6a9eaa32c0dc1b92cac8a085',name:'Salida Prueba',zone:'Guadalajara',start:'2026-09-18',end:'',status:'Propuesta',description:'Prueba de salida',notes:'',participants:[person('Jose','Rockrider 6.3','Pendiente',{companion:true}),person('Jesus','Yami'),organizer('Fernando Fernandez','')],lodgings:[],expenses:[],routes:[]},
 {id:'6a99c6f46ef0815af879555a',name:'Pirineos Aragoneses - Octubre',zone:'Valle de Tena',start:'2026-10-24',end:'',status:'Cancelada',description:'',notes:'',participants:[person('Carlos M.','Husqvarna FE 350','Confirmado',{companion:true}),organizer(),person('Marta S.','','No participa'),person('Javier R.','Beta 430 RR','Pendiente'),person('Laura G.','Yamaha WR 250')],lodgings:[],expenses:[],routes:[]},
 {id:'sierra-morena',name:'Sierra Morena - Primavera',zone:'Despeñaperros',start:'2026-05-15',end:'',status:'Completada',description:'',notes:'',participants:[organizer('Organizador',''),person('Laura G.'),person('Carlos M.')],lodgings:[],expenses:[],routes:[]}
]});}
